
name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
          - "3.12"
        plone:
          - "6.1-latest"
          - "6.0-latest"
          - "5.2-latest"
        exclude:
          - plone: "5.2-latest"
            python: 3.9
          - plone: "5.2-latest"
            python: "3.10"
          - plone: "5.2-latest"
            python: "3.11"
          - plone: "5.2-latest"
            python: "3.12"
          - plone: "6.0-latest"
            python: 3.7
          - plone: "6.0-latest"
            python: "3.12"
          - plone: "6.1-latest"
            python: 3.7
          - plone: "6.1-latest"
            python: 3.8
          - plone: "6.1-latest"
            python: 3.9
          - plone: "6.1-latest"
            python: "3.10"
          - plone: "6.1-latest"
            python: "3.11"

    steps:
    - uses: actions/checkout@v4

    - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
      id: setup
      uses: plone/setup-plone@v2.0.0
      with:
        python-version: ${{ matrix.python }}
        plone-version: ${{ matrix.plone }}

    # Install pas.plugins.authomatic with test extras
    - name: Install pas.plugins.authomatic
      run: |
        pip install ".[test]"

    # test
    - name: Test Codebase
      run: |
        zope-testrunner --auto-color --auto-progress --test-path src
